swagger: '2.0'
info:
  version: 1.0.0
  title: print() Test
  description: |
    <div style="border:1px solid #333; padding:10px; margin:10px 0; background:#f4f4f4; font-family:monospace;">
      <script>print()</script>
    </div>
paths:
  /:
    get:
      responses:
        '200':
          description: OK
